### ISSUE TITLE
Static directory

### ISSUE THREAD

**Issue by raziel2244** [angristan/docker-pleroma#16]
Where should a docker volume/mount be to add files into static? Trying to replace the background and provide some themes but no luck so far :(

I thought it was meant to be /var/lib/pleroma/static but can't see that in the container at all so where is the default background stored?

**Comment by Hallicopter** [comment]
Hey, was facing the same issue. Where did you finally find the static directory with the backgrounds and other frontend matter? I want to apply the Soapbox FE to this, figuring out how to apply it.

**Comment by Hallicopter** [comment]
Okay, I figured it out. For anyone else, do the following:

In the dockerfile, add a line to copy a folder into it. After that, add the following to your config:

```
config :pleroma, :instance,
    static_dir: "<name of copied directory>/"
```

You can store all your frontend matter in that directory and build as usual.
