### ISSUE TITLE
Failed to compile with dependency:majicc

### ISSUE THREAD

**Issue by kokomo123** [angristan/docker-pleroma#18]
Basically, I tried to compile pleroma, and this has caused this one error regarding majicc. I gave it linux-headers in addition, but it's not compiling properly. Also would postgresql-13 be affecting it? should i go lower of a version? 
The full screenshot is below
![error](https://user-images.githubusercontent.com/70863536/96374504-31bdc980-1141-11eb-95eb-141a475ce2a4.PNG)
I'm on the latest version of Debian 10, docker and docker-compose are installed as well. This is in a VM.

**Comment by angristan** [comment]
Thanks for the report, I've added the new dependency to the Dockerfile :)
