### ISSUE TITLE
I have another service running on port 80 and 443 on the server that I am trying to deploy Pleroma on! How do I change Pleroma's ports during setup?

### ISSUE THREAD

**Issue by NotErikUden** [angristan/docker-pleroma#37]
I am also running a Nextcloud instance which already takes up port 80 and port 443. I also have another computer as an NGINX Reverse Proxy, so I do not need an SSL certificate internally, or at least not for the port 443. How do I change that in the config?

**Comment by peterrus** [comment]
I am pretty sure that if you change `docker-compose.yml` like this:

```
,,,
  web:
    build: .
    image: pleroma
    container_name: pleroma_web
    restart: always
    ports:
      - '8888:4000'
,,,
```

In other words. You should be able to map it to whatever port you want. I am not really sure why your instance tries to run on port 443, because that is not how the example docker config is configured right now.

**Comment by NotErikUden** [comment]
Weird. Well, I did not continue using docker-pleroma, but merely continued doing an OTP install which was easier than I thought!
