### ISSUE TITLE
How can I finally change my frontend?

### ISSUE THREAD

**Issue by maste9** [angristan/docker-pleroma#55]
Hello and thanks for the step-by-step walkthrough for hosting pleroma via docker-compose.

Unfortunately I am still struggling with changing the frontend:

 * I added 
 ```
  config :pleroma, :frontends,
  primary: %{
    "name" => "fedi-fe",
    "ref" => "master"
  },
  admin: %{
    "name" => "admin",
    "ref" => "develop"
  }
```
both to the config.exs and to the config-override.exs
 * I put "fedi-fe" as "kenoma" under _Primary_ in Admin FE
   * of course after [activating indatabase configuration](https://docs-develop.pleroma.social/backend/configuration/howto_database_config/) and 
   * testing that successfully by changing the background image.
 * Before I of course unziped and copied the corresponding zip-files into ./static/frontends (e.g. ./static/frontends/kenoma/master)
 * I tried it with
   * `docker-compose build` again
   * `docker-compose down` and `up -d` again
 
But after all I always and forever get the pleroma default frontend. I also don't receive any valuable information regarding this with `docker-compose logs -f` ....

Do you have a hint for me, why I don't get the changes to affect the frontend?

And here an example what happens when I try to install by CMD

```
~ $ ./bin/pleroma_ctl frontend install kenoma --ref mybuild --file /var/lib/pler
oma/static/frontends/tmp/kenoma-master.zip 

20:54:40.658 [info]  Installing kenoma (mybuild) to /var/lib/pleroma/static/frontends/kenoma/mybuild
** (File.CopyError) could not copy recursively from "/var/lib/pleroma/static/frontends/tmp/dist" to "/var/lib/pleroma/static/frontends/kenoma/mybuild". /var/lib/pleroma/static/frontends/tmp/dist: no such file or directory
    (elixir 1.11.4) lib/file.ex:901: File.cp_r!/3
    lib/pleroma/frontend.ex:107: Pleroma.Frontend.install_frontend/3
    lib/pleroma/frontend.ex:39: Pleroma.Frontend.install/2
    (stdlib 3.14.2.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.4) lib/code.ex:341: Code.eval_string_with_error_handling/3
~ $ 
```
I don't get why copying fails - expect there is no directory named dist of course ...

**Comment by maste9** [comment]
OK, found it out myself.
I used the wrong zip-Files from the repos. Now after having used the build artifacts and dist as ref fedi-fe worked immediately 

```
~ $ ./bin/pleroma_ctl frontend install fedife --ref dist --build-url https://git
.pleroma.social/pleroma/fedi-fe/-/jobs/artifacts/master/download?job=build_relea
se 

21:38:58.907 [info]  Downloading pre-built bundle for 

21:39:00.882 [info]  Installing fedife (dist) to /var/lib/pleroma/static/frontends/fedife/dist
~ $ 
```

**Comment by MayhemBill** [comment]
How did you get the front ends  to work? I have them installed, but I can't select them anywhere

**Comment by sanderdatema** [comment]
@maste9 I'd like to know this as well: how to select frontends? Or is it only possible to set one in the config?
