### ISSUE TITLE
Web push keys

### ISSUE THREAD

**Issue by Dekken** [angristan/docker-pleroma#8]
The README.md states the following:

```
Get your web push keys and copy them to secret.exs:
```

I have no idea what these "web push keys" are. 
Can you elaborate pleasE?

**Comment by angristan** [comment]
See https://github.com/danhper/elixir-web-push-encryption / https://developers.google.com/web/updates/2016/03/web-push-encryption?hl=en.

If you're wondering how to generate them, it's simply the command line under the line you pasted!

```
docker-compose run --rm web mix web_push.gen.keypair
```

**Comment by Dekken** [comment]
ahh! of course!
