### ISSUE TITLE
Newest pleroma security update breaks fresh installation

### ISSUE THREAD

**Issue by Jlucu4ka228** [angristan/docker-pleroma#85]
According to new pleroma security update https://pleroma.social/announcements/2023/08/04/pleroma-security-release-2.5.3/

Pleroma is refusing to launch:
``
 ERROR! Config provider Pleroma.Config.ReleaseRuntimeProvider failed with:
 ** (RuntimeError) Configuration at /etc/pleroma/config.exs has world-permissions, execute the following: chmod o= /etc/pleroma/config.exs
     lib/pleroma/config/release_runtime_provider.ex:27: Pleroma.Config.ReleaseRuntimeProvider.load/2
     (elixir 1.11.4) lib/config/provider.ex:347: anonymous fn/2 in Config.Provider.run_providers/2
     (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
     (elixir 1.11.4) lib/config/provider.ex:204: Config.Provider.boot_providers/4
     :init.eval_script/2
     :init.do_boot/3
``
when I execute suggested command, pleroma once again crashes:
``
ERROR! Config provider Pleroma.Config.ReleaseRuntimeProvider failed with:
** (File.Error) could not read file "/etc/pleroma/config.exs": permission denied
    (elixir 1.11.4) lib/file.ex:355: File.read!/1
    (elixir 1.11.4) lib/config/reader.ex:86: Config.Reader.read!/2
    lib/pleroma/config/release_runtime_provider.ex:37: Pleroma.Config.ReleaseRuntimeProvider.load/2
    (elixir 1.11.4) lib/config/provider.ex:347: anonymous fn/2 in Config.Provider.run_providers/2
    (elixir 1.11.4) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.11.4) lib/config/provider.ex:204: Config.Provider.boot_providers/4
    :init.eval_script/2
    :init.do_boot/3
``

I have made chown -R pleroma:pleroma . but it didn't help.

**Comment by Jlucu4ka228** [comment]
Nevermind I did something wrong during installing. Fully rebuilding docker image helped.

**Comment by zen-tools** [comment]
I have the same issue. I fixed it using the following changes:

```diff
$ git diff Dockerfile
diff --git a/Dockerfile b/Dockerfile
index 102e8ea..fa21228 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -34,7 +34,7 @@ RUN echo "import Mix.Config" > config/prod.secret.exs \
     && mkdir release \
     && mix release --path /pleroma
 
-COPY ./config.exs /etc/pleroma/config.exs
+COPY --chown=pleroma --chmod=640 ./config.exs /etc/pleroma/config.exs
 
 EXPOSE 4000
```

**Comment by angristan** [comment]
Please do a PR if you can 🙏
