### ISSUE TITLE
dockerfile not using elixir:1.9

### ISSUE THREAD

**Issue by manikmakki** [angristan/docker-pleroma#9]
During setup following the steps in the readme, I encountered:
** (Mix) You're trying to run :pleroma on Elixir v1.8.2 but it has declared in its mix.exs file it supports only Elixir ~> 1.9

Changed dockerfile from elixir:1.8 to elixir:1.9, and it worked.

**Comment by fanyx** [comment]
latest elixir even is 1.10
would update accordingly
